### ISSUE TITLE
jslint options doesn't work

### ISSUE THREAD

**Issue by saurabhgupta050890** [ajhyndman/vscode-jslint#6]
Any of the settings option doesn't seems to work. Like how do I setup excluded paths with jslint.exlude. 
I tried adding .jslintignore but doesn't work, nor does the .jslintrc

**Comment by jonasmello** [comment]
I have the same ploblem...

**Comment by ajhyndman** [comment]
I'll look into it.  I think I might just not have ever implemented that.

**Comment by ajhyndman** [comment]
This jslint package relies on node-jslint, which it turns out doesn't support a `.jslintignore` or exclusion options.  I think you'd be best to forward requests on to them.

https://github.com/reid/node-jslint/issues/122

**Comment by saurabhgupta050890** [comment]
Its not just .jslintignore. There are many configuration options appears under settings. None of them works. Is there a plan to implement them.

**Comment by jonasmello** [comment]
Options like browser and jquery for example:
![image](https://cloud.githubusercontent.com/assets/1612563/24367491/30cf92e2-12f3-11e7-9a2e-75463c7cef69.png)

**Comment by ajhyndman** [comment]
You're right.  That's my mistake.  :( . Those are actually jshint options that I didn't bother removing when I forked this extension.

I'll be honest, I spent about two days over a weekend forking the Microsoft implementation and getting this working.  I'm no expert at any of what's going on in the internals, and maintaining the extension is not a priority for me at this time.

If anyone is interested in trying to implement some of those features, I'd be more than happy to accept pull requests.  Otherwise, I'll probably remove those options so that it's less confusing in the future.

**Comment by ajhyndman** [comment]
@jonasmello, @saurabhgupta050890:

I'm sure this is way too late to be useful, but I actually took a look at this issue again today.

I didn't change anything, but it looks like `"jslint.exclude"` does work, and can be used as follows:

```
"jslint.excliude": {
  "**/webpack.config.js": true,
  "**/*.demo.js": true,
}
```

Also, most options I tried passing to `"jslint.options"` also work, with the following syntax:

```
"jslint.options": {
  "es6": true,
  "white": true,
  "single": false
}
```

Global variable declarations, like jQuery, can be passed using the "predef" option, like so:

```
"jslint.options": {
  "predef": [
    "$",
    "jquery"
  ]
}
```

I hope anyone with similar issues finds this (belated) response, and it helps.  Otherwise, please let me know if something's still broken.
